/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.Panels;

import controller.AlphabetGame;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import javax.swing.AbstractAction;
import javax.swing.ActionMap;
import javax.swing.InputMap;
import javax.swing.JButton;
import static javax.swing.JComponent.WHEN_IN_FOCUSED_WINDOW;
import javax.swing.KeyStroke;

/**
 *
 * @author actim
 */
public class VowelsPanel extends javax.swing.JPanel {

    AlphabetGame aG;

    public void setAlphabetGame(AlphabetGame aG) {
        this.aG = aG;
        this.resizeButtonFont();
    }

    /**
     * Creates new form LettersPanel
     */
    public VowelsPanel() {
        initComponents();
        
        //Bind keyboard letter to button letter
        keyboardBind(A, KeyEvent.VK_A);
        keyboardBind(E, KeyEvent.VK_E);
        keyboardBind(I, KeyEvent.VK_I);
        keyboardBind(O, KeyEvent.VK_O);
        keyboardBind(U, KeyEvent.VK_U);
        keyboardBind(Y, KeyEvent.VK_Y);
    }
    

    private void keyboardBind(JButton letterButton, int virtualKey) {
        InputMap im = letterButton.getInputMap(WHEN_IN_FOCUSED_WINDOW);
        ActionMap am = letterButton.getActionMap();
        im.put(KeyStroke.getKeyStroke(virtualKey, 0), "clickMe");
        am.put("clickMe", new AbstractAction() {
            public void actionPerformed(ActionEvent e) {
                JButton letterButton = (JButton) e.getSource();
                letterButton.doClick();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        A = new javax.swing.JButton();
        E = new javax.swing.JButton();
        I = new javax.swing.JButton();
        O = new javax.swing.JButton();
        U = new javax.swing.JButton();
        Y = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 255));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });
        setLayout(new java.awt.GridLayout(1, 6));

        A.setText("A");
        A.setFocusable(false);
        A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AActionPerformed(evt);
            }
        });
        add(A);

        E.setText("E");
        E.setFocusable(false);
        E.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EActionPerformed(evt);
            }
        });
        add(E);

        I.setText("I");
        I.setFocusable(false);
        I.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IActionPerformed(evt);
            }
        });
        add(I);

        O.setText("O");
        O.setFocusable(false);
        O.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OActionPerformed(evt);
            }
        });
        add(O);

        U.setText("U");
        U.setFocusable(false);
        U.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UActionPerformed(evt);
            }
        });
        add(U);

        Y.setText("Y");
        Y.setFocusable(false);
        Y.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YActionPerformed(evt);
            }
        });
        add(Y);
    }// </editor-fold>//GEN-END:initComponents

    private void AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AActionPerformed

        char charE = evt.getActionCommand().charAt(0);
        aG.sendAnswer(charE);
        
    }//GEN-LAST:event_AActionPerformed

    private void EActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EActionPerformed
        aG.sendAnswer('E');
    }//GEN-LAST:event_EActionPerformed

    private void IActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IActionPerformed
        aG.sendAnswer('I');
    }//GEN-LAST:event_IActionPerformed

    private void OActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OActionPerformed
        aG.sendAnswer('O');
    }//GEN-LAST:event_OActionPerformed

    private void UActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UActionPerformed
        aG.sendAnswer('U');
    }//GEN-LAST:event_UActionPerformed

    private void YActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YActionPerformed
        aG.sendAnswer('Y');
    }//GEN-LAST:event_YActionPerformed

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        // TODO add your handling code here:
        this.resizeButtonFont();
    }//GEN-LAST:event_formComponentResized
    private void resizeButtonFont() {
        int width = this.getWidth();
        A.setFont(new Font("Arial", Font.PLAIN, width / 40));
        E.setFont(new Font("Arial", Font.PLAIN, width / 40));
        I.setFont(new Font("Arial", Font.PLAIN, width / 40));
        O.setFont(new Font("Arial", Font.PLAIN, width / 40));
        U.setFont(new Font("Arial", Font.PLAIN, width / 40));
        Y.setFont(new Font("Arial", Font.PLAIN, width / 40));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton A;
    private javax.swing.JButton E;
    private javax.swing.JButton I;
    private javax.swing.JButton O;
    private javax.swing.JButton U;
    private javax.swing.JButton Y;
    // End of variables declaration//GEN-END:variables
}
