/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.AlphabetGame;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import javax.swing.AbstractAction;
import javax.swing.ActionMap;
import javax.swing.InputMap;
import javax.swing.JButton;
import static javax.swing.JComponent.WHEN_IN_FOCUSED_WINDOW;
import javax.swing.JPanel;
import javax.swing.KeyStroke;
import observer.Observer;

/**
 *
 * @author actim
 */
public class MainFrame extends javax.swing.JFrame implements Observer {

    private AlphabetGame alphabetGame;
    private String font = "ARIAL";

    public MainFrame(AlphabetGame alphabetGame) {

        this.alphabetGame = alphabetGame;
        initComponents();

        Pnl_Global.removeAll();
        Pnl_Global.repaint();
        Pnl_Global.revalidate();

        //Adding Pannels
        Pnl_Global.add(Pnl_MainMenu);
        Pnl_Global.repaint();
        Pnl_Global.revalidate();

        keyboardBind(Btn_Exit, KeyEvent.VK_ESCAPE);

        this.setVisible(true);
    }

    private void changePanel(JPanel namePanel) {
        Pnl_Global.removeAll();
        Pnl_Global.repaint();
        Pnl_Global.revalidate();

        //Adding Pannels
        Pnl_Global.add(namePanel);
        Pnl_Global.repaint();
        Pnl_Global.revalidate();

        if (namePanel == Pnl_LettersMenu) {
            keyboardBind(Btn_Cancel_Letters, KeyEvent.VK_ESCAPE);
        }

        if (namePanel == Pnl_Game) {
            keyboardBind(Btn_ReturnMenu, KeyEvent.VK_ESCAPE);
            keyboardBind(Btn_PlayLetter, KeyEvent.VK_SPACE);
        }
        if (namePanel == Pnl_Score) {
            keyboardBind(Btn_QuitScore, KeyEvent.VK_ESCAPE);
        }
    }

    private void keyboardBind(JButton letterButton, int virtualKey) {
        InputMap im = letterButton.getInputMap(WHEN_IN_FOCUSED_WINDOW);
        ActionMap am = letterButton.getActionMap();
        im.put(KeyStroke.getKeyStroke(virtualKey, 0), "clickMe");
        am.put("clickMe", new AbstractAction() {
            public void actionPerformed(ActionEvent e) {
                JButton letterButton = (JButton) e.getSource();
                letterButton.doClick();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        Pnl_Global = new javax.swing.JPanel();
        Pnl_Score = new javax.swing.JPanel();
        Lbl_FinalScoreVar = new javax.swing.JLabel();
        Lbl_FinalScoreFix = new javax.swing.JLabel();
        Btn_QuitScore = new javax.swing.JButton();
        Pnl_Game = new javax.swing.JPanel();
        Pnl_TopGame = new javax.swing.JPanel();
        Lbl_TimerFixed = new javax.swing.JLabel();
        Lbl_TimerVar = new javax.swing.JLabel();
        Btn_PlayLetter = new javax.swing.JButton();
        Lbl_ScoreFixed = new javax.swing.JLabel();
        Lbl_ScoreVar = new javax.swing.JLabel();
        Pnl_BotGame = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        Btn_ReturnMenu = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        Pnl_CenGame = new javax.swing.JPanel();
        Pnl_KeyBoard = new javax.swing.JPanel();
        alphabetPanel1 = new view.Panels.AlphabetPanel();
        consonnantsPanel1 = new view.Panels.ConsonnantsPanel();
        vowelsPanel1 = new view.Panels.VowelsPanel();
        Pnl_LettersMenu = new javax.swing.JPanel();
        Lbl_Letters = new javax.swing.JLabel();
        Btn_Alphabet = new javax.swing.JToggleButton();
        Btn_Vowels = new javax.swing.JToggleButton();
        Btn_Consonnants = new javax.swing.JToggleButton();
        Lbl_Mode = new javax.swing.JLabel();
        Btn_Training = new javax.swing.JButton();
        Btn_Chrono = new javax.swing.JButton();
        Btn_Cancel_Letters = new javax.swing.JButton();
        Pnl_MainMenu = new javax.swing.JPanel();
        Btn_Play = new javax.swing.JButton();
        Btn_Options = new javax.swing.JButton();
        Btn_Exit = new javax.swing.JButton();
        Lbl_Title = new javax.swing.JLabel();
        Lbl_Credits = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 500));
        setPreferredSize(new java.awt.Dimension(900, 600));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });

        Pnl_Global.setMinimumSize(new java.awt.Dimension(600, 400));
        Pnl_Global.setLayout(new java.awt.CardLayout());

        Pnl_Score.setLayout(new java.awt.GridBagLayout());

        Lbl_FinalScoreVar.setText("x");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        Pnl_Score.add(Lbl_FinalScoreVar, gridBagConstraints);

        Lbl_FinalScoreFix.setText("Your score:");
        Pnl_Score.add(Lbl_FinalScoreFix, new java.awt.GridBagConstraints());

        Btn_QuitScore.setText("Return Menu");
        Btn_QuitScore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_QuitScoreActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        Pnl_Score.add(Btn_QuitScore, gridBagConstraints);

        Pnl_Global.add(Pnl_Score, "card5");

        Pnl_Game.setMinimumSize(new java.awt.Dimension(600, 500));
        Pnl_Game.setLayout(new java.awt.BorderLayout());

        Pnl_TopGame.setLayout(new java.awt.GridBagLayout());

        Lbl_TimerFixed.setText("Timer:");
        Pnl_TopGame.add(Lbl_TimerFixed, new java.awt.GridBagConstraints());

        Lbl_TimerVar.setText("0s");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        Pnl_TopGame.add(Lbl_TimerVar, gridBagConstraints);

        Btn_PlayLetter.setText("Play Letter (Press Space)");
        Btn_PlayLetter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_PlayLetterActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        Pnl_TopGame.add(Btn_PlayLetter, gridBagConstraints);

        Lbl_ScoreFixed.setText("Score:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        Pnl_TopGame.add(Lbl_ScoreFixed, gridBagConstraints);

        Lbl_ScoreVar.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        Pnl_TopGame.add(Lbl_ScoreVar, gridBagConstraints);

        Pnl_Game.add(Pnl_TopGame, java.awt.BorderLayout.PAGE_START);

        Pnl_BotGame.setLayout(new java.awt.GridLayout(1, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        Pnl_BotGame.add(jPanel1);

        Btn_ReturnMenu.setText("Return Menu");
        Btn_ReturnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ReturnMenuActionPerformed(evt);
            }
        });
        Pnl_BotGame.add(Btn_ReturnMenu);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        Pnl_BotGame.add(jPanel2);

        Pnl_Game.add(Pnl_BotGame, java.awt.BorderLayout.PAGE_END);

        Pnl_CenGame.setLayout(new java.awt.GridBagLayout());

        Pnl_KeyBoard.setLayout(new java.awt.CardLayout());
        Pnl_KeyBoard.add(alphabetPanel1, "card2");
        Pnl_KeyBoard.add(consonnantsPanel1, "card3");
        Pnl_KeyBoard.add(vowelsPanel1, "card4");

        Pnl_CenGame.add(Pnl_KeyBoard, new java.awt.GridBagConstraints());

        Pnl_Game.add(Pnl_CenGame, java.awt.BorderLayout.CENTER);

        Pnl_Global.add(Pnl_Game, "card3");

        Pnl_LettersMenu.setPreferredSize(new java.awt.Dimension(900, 600));
        Pnl_LettersMenu.setLayout(new java.awt.GridBagLayout());

        Lbl_Letters.setText("Choose your letters:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        Pnl_LettersMenu.add(Lbl_Letters, gridBagConstraints);

        Btn_Alphabet.setText("Alphabet");
        Btn_Alphabet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_AlphabetActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        Pnl_LettersMenu.add(Btn_Alphabet, gridBagConstraints);

        Btn_Vowels.setText("Vowels");
        Btn_Vowels.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_VowelsActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        Pnl_LettersMenu.add(Btn_Vowels, gridBagConstraints);

        Btn_Consonnants.setText("Consonnants");
        Btn_Consonnants.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ConsonnantsActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        Pnl_LettersMenu.add(Btn_Consonnants, gridBagConstraints);

        Lbl_Mode.setText("Mode:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        Pnl_LettersMenu.add(Lbl_Mode, gridBagConstraints);

        Btn_Training.setText("Training");
        Btn_Training.setEnabled(false);
        Btn_Training.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_TrainingActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        Pnl_LettersMenu.add(Btn_Training, gridBagConstraints);

        Btn_Chrono.setText("Chrono 30'");
        Btn_Chrono.setEnabled(false);
        Btn_Chrono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ChronoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        Pnl_LettersMenu.add(Btn_Chrono, gridBagConstraints);

        Btn_Cancel_Letters.setText("Cancel");
        Btn_Cancel_Letters.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Cancel_LettersActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        Pnl_LettersMenu.add(Btn_Cancel_Letters, gridBagConstraints);

        Pnl_Global.add(Pnl_LettersMenu, "card4");

        Pnl_MainMenu.setPreferredSize(new java.awt.Dimension(900, 600));
        Pnl_MainMenu.setLayout(new java.awt.GridBagLayout());

        Btn_Play.setText("Play");
        Btn_Play.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_PlayActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        Pnl_MainMenu.add(Btn_Play, gridBagConstraints);

        Btn_Options.setText("Options");
        Btn_Options.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_OptionsActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        Pnl_MainMenu.add(Btn_Options, gridBagConstraints);

        Btn_Exit.setText("Exit");
        Btn_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ExitActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        Pnl_MainMenu.add(Btn_Exit, gridBagConstraints);

        Lbl_Title.setText("Alpha Training");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        Pnl_MainMenu.add(Lbl_Title, gridBagConstraints);

        Lbl_Credits.setText("Credits: Mel-Srt");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LAST_LINE_END;
        Pnl_MainMenu.add(Lbl_Credits, gridBagConstraints);

        Pnl_Global.add(Pnl_MainMenu, "card4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Pnl_Global, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Pnl_Global, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_OptionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_OptionsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_OptionsActionPerformed

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        int width = this.getWidth();
        int heigth = this.getHeight();
        //Panel Main Menu
        Lbl_Title.setFont(new Font(font, Font.PLAIN, width / 8));
        Btn_Play.setFont(new Font(font, Font.PLAIN, width / 40));
        Btn_Options.setFont(new Font(font, Font.PLAIN, width / 40));
        Btn_Options.setVisible(false);
        Btn_Exit.setFont(new Font(font, Font.PLAIN, width / 40));
        Lbl_Credits.setFont(new Font(font, Font.PLAIN, width / 45));

        //Panel Letters Menu
        Lbl_Letters.setFont(new Font(font, Font.PLAIN, width / 40));
        Btn_Alphabet.setFont(new Font(font, Font.PLAIN, width / 40));
        Btn_Vowels.setFont(new Font(font, Font.PLAIN, width / 40));
        Btn_Consonnants.setFont(new Font(font, Font.PLAIN, width / 40));
        Lbl_Mode.setFont(new Font(font, Font.PLAIN, width / 40));
        Btn_Training.setFont(new Font(font, Font.PLAIN, width / 40));
        Btn_Chrono.setFont(new Font(font, Font.PLAIN, width / 40));
        Btn_Cancel_Letters.setFont(new Font(font, Font.PLAIN, width / 40));

        //Panel Game
        Btn_ReturnMenu.setFont(new Font(font, Font.PLAIN, width / 40));
        Btn_PlayLetter.setFont(new Font(font, Font.PLAIN, width / 40));
        Lbl_ScoreFixed.setFont(new Font(font, Font.PLAIN, width / 40));
        Lbl_ScoreVar.setFont(new Font(font, Font.PLAIN, width / 30));
        Lbl_TimerFixed.setFont(new Font(font, Font.PLAIN, width / 40));
        Lbl_TimerVar.setFont(new Font(font, Font.PLAIN, width / 30));
        Pnl_KeyBoard.setPreferredSize(new Dimension((width / 2) + 200, (heigth / 2)));

        //Panel SCore
        Btn_QuitScore.setFont(new Font(font, Font.PLAIN, width / 40));
        Lbl_FinalScoreFix.setFont(new Font(font, Font.PLAIN, width / 30));
        Lbl_FinalScoreVar.setFont(new Font(font, Font.PLAIN, width / 30));
    }//GEN-LAST:event_formComponentResized

    private void Btn_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ExitActionPerformed
        dispose();
    }//GEN-LAST:event_Btn_ExitActionPerformed

    private void Btn_PlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_PlayActionPerformed
        changePanel(Pnl_LettersMenu);
    }//GEN-LAST:event_Btn_PlayActionPerformed

    private void Btn_Cancel_LettersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Cancel_LettersActionPerformed
        changePanel(Pnl_MainMenu);
    }//GEN-LAST:event_Btn_Cancel_LettersActionPerformed

    private void Btn_AlphabetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_AlphabetActionPerformed

        if (Btn_Alphabet.isSelected()) {
            this.alphabetGame.getDataGame().setGameType("Standard A-Z");
            Btn_Vowels.setSelected(false);
            Btn_Consonnants.setSelected(false);
            Btn_Training.setEnabled(true);
            Btn_Chrono.setEnabled(true);
        } else {
            Btn_Training.setEnabled(false);
            Btn_Chrono.setEnabled(false);
        }
    }//GEN-LAST:event_Btn_AlphabetActionPerformed

    private void Btn_VowelsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_VowelsActionPerformed

        if (Btn_Vowels.isSelected()) {
            this.alphabetGame.getDataGame().setGameType("Vowels");
            Btn_Alphabet.setSelected(false);
            Btn_Consonnants.setSelected(false);
            Btn_Training.setEnabled(true);
            Btn_Chrono.setEnabled(true);
        } else {
            Btn_Training.setEnabled(false);
            Btn_Chrono.setEnabled(false);
        }
    }//GEN-LAST:event_Btn_VowelsActionPerformed

    private void Btn_ConsonnantsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ConsonnantsActionPerformed
        // TODO add your handling code here:
        if (Btn_Consonnants.isSelected()) {
            this.alphabetGame.getDataGame().setGameType("Consonnants");
            Btn_Alphabet.setSelected(false);
            Btn_Vowels.setSelected(false);
            Btn_Training.setEnabled(true);
            Btn_Chrono.setEnabled(true);
        } else {
            Btn_Training.setEnabled(false);
            Btn_Chrono.setEnabled(false);
        }
    }//GEN-LAST:event_Btn_ConsonnantsActionPerformed

    private void loadGameFrame(boolean isTrainingMode) {
        alphabetGame.getDataGame().setTrainingMode(isTrainingMode);
        alphabetGame.start();
        changePanel(Pnl_Game);
        if(isTrainingMode){
            Lbl_ScoreFixed.setVisible(false);
            Lbl_ScoreVar.setVisible(false);
            Lbl_TimerFixed.setVisible(false);
            Lbl_TimerVar.setVisible(false);
        }
        else{
            Lbl_ScoreFixed.setVisible(true);
            Lbl_ScoreVar.setVisible(true);
            Lbl_TimerFixed.setVisible(true);
            Lbl_TimerVar.setVisible(true);
        }
        changeKeyBoard(alphabetGame.getDataGame().getGameType());
    }

    private void changeKeyBoard(int mode) {
        Pnl_KeyBoard.removeAll();
        Pnl_KeyBoard.repaint();
        Pnl_KeyBoard.revalidate();
        switch (mode) {
            case 2:
                vowelsPanel1.setAlphabetGame(alphabetGame);
                Pnl_KeyBoard.add(vowelsPanel1);
                break;
            case 3:
                consonnantsPanel1.setAlphabetGame(alphabetGame);
                Pnl_KeyBoard.add(consonnantsPanel1);
                break;
            default:
                alphabetPanel1.setAlphabetGame(alphabetGame);
                Pnl_KeyBoard.add(alphabetPanel1);
                break;
        }
    }
    private void Btn_TrainingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_TrainingActionPerformed
        loadGameFrame(true);
    }//GEN-LAST:event_Btn_TrainingActionPerformed

    private void Btn_ChronoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ChronoActionPerformed
        loadGameFrame(false);
    }//GEN-LAST:event_Btn_ChronoActionPerformed

    private void Btn_ReturnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ReturnMenuActionPerformed
        alphabetGame.stop();
        changePanel(Pnl_MainMenu);
    }//GEN-LAST:event_Btn_ReturnMenuActionPerformed

    private void Btn_PlayLetterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_PlayLetterActionPerformed
        alphabetGame.playLetter();
    }//GEN-LAST:event_Btn_PlayLetterActionPerformed

    private void Btn_QuitScoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_QuitScoreActionPerformed
        changePanel(Pnl_MainMenu);
    }//GEN-LAST:event_Btn_QuitScoreActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton Btn_Alphabet;
    private javax.swing.JButton Btn_Cancel_Letters;
    private javax.swing.JButton Btn_Chrono;
    private javax.swing.JToggleButton Btn_Consonnants;
    private javax.swing.JButton Btn_Exit;
    private javax.swing.JButton Btn_Options;
    private javax.swing.JButton Btn_Play;
    private javax.swing.JButton Btn_PlayLetter;
    private javax.swing.JButton Btn_QuitScore;
    private javax.swing.JButton Btn_ReturnMenu;
    private javax.swing.JButton Btn_Training;
    private javax.swing.JToggleButton Btn_Vowels;
    private javax.swing.JLabel Lbl_Credits;
    private javax.swing.JLabel Lbl_FinalScoreFix;
    private javax.swing.JLabel Lbl_FinalScoreVar;
    private javax.swing.JLabel Lbl_Letters;
    private javax.swing.JLabel Lbl_Mode;
    private javax.swing.JLabel Lbl_ScoreFixed;
    private javax.swing.JLabel Lbl_ScoreVar;
    private javax.swing.JLabel Lbl_TimerFixed;
    private javax.swing.JLabel Lbl_TimerVar;
    private javax.swing.JLabel Lbl_Title;
    private javax.swing.JPanel Pnl_BotGame;
    private javax.swing.JPanel Pnl_CenGame;
    private javax.swing.JPanel Pnl_Game;
    private javax.swing.JPanel Pnl_Global;
    private javax.swing.JPanel Pnl_KeyBoard;
    private javax.swing.JPanel Pnl_LettersMenu;
    private javax.swing.JPanel Pnl_MainMenu;
    private javax.swing.JPanel Pnl_Score;
    private javax.swing.JPanel Pnl_TopGame;
    private view.Panels.AlphabetPanel alphabetPanel1;
    private view.Panels.ConsonnantsPanel consonnantsPanel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private view.Panels.VowelsPanel vowelsPanel1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(String string) {
    }

    @Override
    public void updateTimer(String string) {
        Lbl_TimerVar.setText(string);
    }

    @Override
    public void updateScore(String string) {
        Lbl_ScoreVar.setText(string);
    }

    @Override
    public void updateEndGame(String score) {
        Lbl_FinalScoreVar.setText(score);
        changePanel(Pnl_Score);
    }
}
